[package]
name = "DragonClaw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.18"
rustyline = "13.0.0"
tokio = { version = "1", features = ["full"] }
